version: '2'

services:
  recommender:
    build: ./recommender
    env_file: ./recommender/.env
    volumes:
      - ./recommender:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - redis
      - crawler
    depends_on:
      - recommender-db
      - redis
    environment:
      - DASHBOARD_PORT=3000
  recommender-db:
    image: zsoltm/postgresql-armhf
    restart: always
  crawler:
    build: ./crawler
    env_file: ./crawler/.env
    volumes:
      - ./crawler:/usr/src/app
    depends_on:
      - crawler-db
      - redis
    links:
      - crawler-db
      - redis
  crawler-db:
    image: zsoltm/postgresql-armhf
    restart: always
  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
    env_file: config.env
    environment:
      - PORT=8000
    ports:
      - "80:8000"
    links:
      - crawler
      - recommender
  redis:
    image: aerodame/armhf-redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
