version: '3'

services:
  recommender:
    build: ./recommender
    volumes:
      - ./recommender:/usr/src/app
    links:
      - redis
    environment:
      - DASHBOARD_PORT=3000
  recommender-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
  crawler:
    build: ./crawler
    env_file: ./crawler/.env
    volumes:
      - ./crawler:/usr/src/app
    depends_on:
      - crawler-db
    links:
      - crawler-db
  crawler-db:
    image: postgres
    restart: always
  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
    env_file: config.env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
  redis:
    image: redis
    restart: always
    ports:
      - "6379"
