version: '3'

services:
  recommender:
    build: ./recommender
    env_file: ./recommender/.env
    volumes:
      - ./recommender:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - redis
      - crawler
    environment:
      - DASHBOARD_PORT=3000
  recommender-db:
    image: postgres
    restart: always
  crawler:
    build: ./crawler
    env_file: ./crawler/.env
    volumes:
      - ./crawler:/usr/src/app
    depends_on:
      - crawler-db
      - redis
    links:
      - crawler-db
      - redis
  crawler-db:
    image: postgres
    restart: always
  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
    env_file: config.env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    links:
      - crawler
      - recommender
  redis:
    image: redis
    restart: always
