recommender:
  build: ./services/recommender
  volumes:
    - ./shared:/usr/src/app/shared
    - ./services/recommender:/usr/src/app
  links:
    - redis
    - db
  environment:
    - DASHBOARD_PORT=3000
  ports:
    - "3000:3000"
ui:
  build: ./services/ui
  volumes:
    - ./shared:/usr/src/app/shared
    - ./services/ui:/usr/src/app
  links:
    - redis
    - db
  environment:
    - PORT=8000
  ports:
    - "8000:8000"
redis:
  image: redis
  ports:
    - "6379"
db:
  image: postgres
  ports:
    - "5432"
